source 'http://rubygems.org'

gem 'activerecord', '5.2', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'

gem 'sinatra'
gem 'sqlite3', '~>1.3.6'
gem 'tux'
gem 'pry'
gem 'pry-nav'
gem 'rake'
gem 'rspec'
gem 'rack-test'
gem 'database_cleaner', '~> 1.5', '>= 1.5.3'
gem 'require_all'
